#!/bin/bash
# vendor: Tony Lip(scott)


MYNAME=$(basename $0)
[ -f /etc/haenv ] && . /etc/haenv
RES_GLOBAL_LIBS="defs cmd_defs functions log drbd_lib"

RES_GLOBAL_LIBDIR=$PREFIX/resource/globals

for lib in $RES_GLOBAL_LIBS; do
    if [ -f $RES_GLOBAL_LIBDIR/$lib ] ; then
        . $RES_GLOBAL_LIBDIR/$lib
    else
        log_err "resource libary $lib is missing"
    fi
done

validate()
{
    if ! echo "$HA_RESKEY_drbd_name" | grep "^drbd" >/dev/null;then
        log_err "The drbd_name must set to drbd resource name, for example drbd0"
        return 1
    fi
    return 0
}

start()
{
    if status;then
        return 0
    fi

    for i in seq 3;do
        if ! status;then
            sleep 1
            continue
        fi
        return 0
    done
    return 1
}
stop()
{
    return 0
}
status()
{
    if [ ! -f "/proc/drbd" ];then
        log_err "Drbd resource hasn't up yet"
        return 1
    fi

    local drbd_info
    local minor
    local cstate

    drbd_info=$(cat /proc/drbd)
    minor=$(get_drbd_minor "$HA_RESKEY_drbd_name")
    cstate=$(get_drbd_cstate "$minor" "$drbd_info")

    if [ "$cstate" = "Connected" ];then
        return 0
    fi

    log_err "Current cstate is not Connected"
    log_err "$drbd_info"
    return 1
}

typeset action=$1

if ! validate;then
    if [ "$action" = "stop" -o "$action" = "forcestop" ];then
        exit 0
    fi
    exit 1
fi

case "$action" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    alive)
        status
        ;;
    check_env)
        status
        ;;
    *)
        exit 1
esac